name: utils 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jinja2
  - pandas
  - netcdf4
  - numpy=2.1
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - pytest
  - pip
  - xarray
  - xesmf
  - pip:
    - -e .